export const data = {
  appetizers: [
    {
      id: 1,
      title: "Crab Wanton",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "Deep fried wanton",
      price: 6.99,
      // rating: 4.5,
    },
    {
      id: 2,
      title: "Pot Stickers",
      image: "./assets/menu/meal-3.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "Savory pot stickers",
      price: 6.99,
      // rating: 4.5,
    },
    {
      id: 3,
      title: "Egg Rolls",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Vegetarian",
      tag: "vegetarian",
      description: "Veggie egg rolls",
      price: 6.99,
      // rating: 4.5,
    },
    {
      id: 4,
      title: "Veggie Tempura",
      image: "./assets/menu/meal-3.jpg",
      tagTitle: "Vegetarian",
      tag: "vegetarian",
      description: "Deep fried veggies",
      price: 8.99,
      // rating: 4.5,
    },
    {
      id: 5,
      title: "Chicken Wings",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Fried chicken wings",
      price: 8.99,
      // rating: 4.5,
    },
    {
      id: 6,
      title: "Fried Shrimp",
      image: "./assets/menu/meal-3.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Deep fried prawns",
      price: 8.99,
      // rating: 4.5,
    },
    {
      id: 7,
      title: "Sweet Potatoes",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Sweet Potato fries",
      price: 5.99,
      // rating: 4.5,
    },
    {
      id: 8,
      title: "French Fries",
      image: "./assets/menu/meal-3.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Classic french fries",
      price: 5.99,
      // rating: 4.5,
    },
  ],

  desserts: [
    {
      id: 1,
      title: "Happy Ice Cream Cup",
      image: "./assets/menu/meal-3.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Ice Cream Dessert",
      price: 6.99,
      // rating: 4.5,
    },
    {
      id: 2,
      title: "Happy Banana Split",
      image: "./assets/menu/meal-3.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Scrumptious treat",
      price: 8.99,
      // rating: 4.5,
    },
    {
      id: 3,
      title: "Happy Waffle Ice Cream Cone",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Waffle cone",
      price: 5.99,
      // rating: 4.5,
    },
    {
      id: 4,
      title: "Happy Waffle Ice Cream Cone",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Chocolate syrup",
      price: 5.99,
      // rating: 4.5,
    },
    {
      id: 5,
      title: "Happy Waffle ",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Chocolate syrup",
      price: 8.99,
      // rating: 4.5,
    },
    {
      id: 5,
      title: "Happy Birthday ",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Birthday dessert",
      price: "0 Free with id",
      // rating: 4.5,
    },
  ],

  noodles: [
    {
      id: 1,
      title: "Chow Mein",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "Stir fried egg noodle",
      price: 12.99,
      options: "Chicken, Beef, or Pork",
      // rating: 4.5,
    },
    {
      id: 2,
      title: "Pad Thai",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Classic thai rice noodle stir fry",
      price: 12.99,
      options: "Chicken, Beef, or Pork",
      // rating: 4.5,
    },
    {
      id: 3,
      title: "Druken Noodle",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Spicy stir-fry rice noodles",
      price: 12.99,
      options: "Chicken, Beef, or Pork",
      // rating: 4.5,
    },
  ],

  entrees: [
    {
      id: 1,
      title: "Fresh Broccoli",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "In oyster sauce",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 2,
      title: "Spicy Basil",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "Sweet and spicy",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 3,
      title: "Mixed Vegetales",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "In a garlic sauce",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 4,
      title: "Golden Chicken",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "Crispy fried",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 5,
      title: "Orange Chicken",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "Orange juice marinated",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 6,
      title: "Cashew Nuts",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "Stir fried to perfection",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 7,
      title: "Garlic Pepper",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "Stir fried to perfection",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 8,
      title: "Deep Fried Sole",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Asian Fusion",
      tag: "asianFusion",
      description: "With sweet, spicy sauce",
      price: 15.99,
      // rating: 4.5,
    },
  ],

  salads: [
    {
      id: 1,
      title: "House Salad",
      image: "./assets/menu/veggies.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Green salad with dressing",
      price: 7.99,
      // rating: 4.5,
    },
    {
      id: 2,
      title: "Spicy Beef Salad",
      image: "./assets/menu/veggies.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Spicy lime dressing",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 3,
      title: "Spicy Shrimp Salad",
      image: "./assets/menu/veggies.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Spicy lime dressing",
      price: 15.99,
      // rating: 4.5,
    },
  ],

  rice: [
    {
      id: 1,
      title: "Rim Nam Fried Rice",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Your choice of meats",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 2,
      title: "Rim Nam Combination Rice",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Chicken, shrimp, eggs",
      price: 15.99,
      // rating: 4.5,
    },
    {
      id: 3,
      title: "Rim Nam Spicy Basil Rice",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Your choice of meats",
      price: 12.99,
      // rating: 4.5,
    },
    {
      id: 4,
      title: "Rim Nam Pineapple Rice",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Your choice of meats",
      price: 15.99,
      // rating: 4.5,
    },
  ],

  soups: [
    {
      id: 1,
      title: "Tom Yum Soup",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Spicy and sour soup",
      price: "Your choice of chicken or veggies",
      // rating: 4.5,
    },
    {
      id: 2,
      title: "Tom Kha Soup",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Spicy coconut soup",
      price: "Your choice of chicken or veggies",
      // rating: 4.5,
    },
    {
      id: 3,
      title: "Vegetable Soup",
      image: "./assets/menu/meal-1.jpg",
      tagTitle: "Thai",
      tag: "thai",
      description: "Fresh cut veggies",
      price: "Your choice of chicken or veggies",
      // rating: 4.5,
    },
  ],
};
